#!/bin/bash
set -e

echo "Running E2E Docker Tests..."
cd e2e
docker-compose up --build --abort-on-container-exit
cd ..

echo "Formatting benchmark results..."
# Extract the relevant timing info from the output
if [ -f e2e_benchmark.txt ]; then
    TIME_STR=$(grep "Elapsed (wall clock) time" e2e_benchmark.txt | awk -F': ' '{print $2}')
    MEM_STR=$(grep "Maximum resident set size" e2e_benchmark.txt | awk -F': ' '{print $2}')

    cat << EOF > e2e_benchmark.md
## 🚀 E2E Performance Benchmark

**Dataset:** 1M elements (1000x1000) Zarr array with coordinates and missing data.
**Query:** \`SELECT SUM(value) FROM read_zarr('/data/test.zarr');\`

- **Wall Clock Time:** $TIME_STR
- **Max Memory (RSS):** $MEM_STR kb

*Generated by automated E2E testing locally.*
EOF
    rm e2e_benchmark.txt
    echo "Benchmark saved to e2e_benchmark.md"
else
    echo "Benchmark failed to generate."
    exit 1
fi
