[book]
authors = ["Climate X"]
language = "en"
src = "src"
title = "Eider Documentation"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/dnf0/eider"
edit-url-template = "https://github.com/dnf0/eider/edit/main/docs/src/{path}"
