name: Pre-Commit & Unit Test

on:
  - pull_request
  - workflow_dispatch

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-checks:
    name: CI Checks
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo registry
        uses: actions/cache@v4
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo index
        uses: actions/cache@v4
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}

      - name: Cache Cargo build
        uses: actions/cache@v4
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}

      - name: Install Python
        uses: actions/setup-python@v5

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        with:
          extra_args: --all-files

      - name: Install duckdb-ext-tools
        run: cargo install cargo-duckdb-ext-tools --force

      - name: Build extension and test
        run: |
          cargo duckdb-ext build
          cargo test --no-default-features
